name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Backend and Frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH Key
      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > staging-bcc-key.pem
          chmod 600 staging-bcc-key.pem

      # Step 3: Add Host Key to Known Hosts
      - name: Add Host Key to Known Hosts
        env:
          SERVER_HOST: "staging.brickcityconnect.com"  # Replace with your server's domain or IP
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      # Step 4: Build React Frontend
      - name: Build React Frontend
        working-directory: ./client
        env:
          REACT_APP_SERVER_URL: "https://staging.brickcityconnect.com"
          REACT_APP_BUGSNAG_API_KEY: ${{ secrets.REACT_APP_BUGSNAG_API_KEY }}
          REACT_APP_ENV: "staging"
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_CONFIGCAT_SDK_KEY: ${{ secrets.REACT_APP_CONFIGCAT_SDK_KEY }}
          REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID }}
          REACT_APP_DISCORD_REDIRECT_URI: ${{ secrets.REACT_APP_DISCORD_REDIRECT_URI }}
          REACT_APP_TURN_SERVER_CREDENTIAL: ${{ secrets.REACT_APP_TURN_SERVER_CREDENTIAL }}
          REACT_APP_TURN_SERVER_USERNAME: ${{ secrets.REACT_APP_TURN_SERVER_USERNAME }}
        run: |
          npm install
          npm run build

      # Step 5: Deploy React Frontend
      - name: Deploy React Frontend
        env:
          SERVER_USER: "ec2-user"
          SERVER_HOST: "staging.brickcityconnect.com"
          DEPLOY_PATH: "/home/ec2-user/rit-omegle/client/build"
        run: |
          rsync -avz -e "ssh -i staging-bcc-key.pem" ./client/build/ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH

      # Step 6: Deploy Node.js Backend
      - name: Deploy Node.js Backend
        env:
          SERVER_USER: "ec2-user"
          SERVER_HOST: "staging.brickcityconnect.com"
          DEPLOY_PATH: "/home/ec2-user/rit-omegle/server"
        run: |
          rsync -avz -e "ssh -i staging-bcc-key.pem" ./server/ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH

      # Step 7: Install Backend Dependencies and Restart
      - name: Install Backend Dependencies and Restart
        env:
          SERVER_USER: "ec2-user"
          SERVER_HOST: "staging.brickcityconnect.com"
        run: |
          ssh -i staging-bcc-key.pem $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /home/ec2-user/rit-omegle/server
          npm install
          pm2 restart src/server.js
          EOF

      # Step 8: Cleanup
      - name: Cleanup
        run: rm -f staging-bcc-key.pem